name: CommandLog
version: 1.1.5
main: io.github.meeples10.commandlog.Main
author: Meeples10
description: CommandLog

commands:
  commandlog:
    aliases: [cl]
    description: A simple command logger.
    usage: Type '/cl help' to show the help information.

permissions:
    commandlog.admin:
        description: Gives access to all CommandLog commands
        children:
            commandlog.history: true
            commandlog.notice: true
        default: admin
    commandlog.history:
        description: Allows a user to see the history of commands that were executed
    commandlog.notice:
        description: Allows a user to be notified when a command is executed