name: CommandLog
version: 2.0.1
main: io.github.meeples10.commandlog.Main
author: Meeples10
description: Allows players to view the commands used by others.
depend: [MeepCore]
api-version: 1.14
commands:
  commandlog:
    aliases: [cl]
    description: Allows players to view commands used by others.
    usage: Use '/cl help' to show help information.
permissions:
  commandlog.notice:
    description: Allows players to be notified when a command is executed
    default: op
  commandlog.reload:
    description: Allows players to reload the plugin
    default: op
