name: CommandLog
main: io.github.meeples10.commandlog.Main
version: %PROJECT_VERSION%
author: Meeples10
description: %PROJECT_DESCRIPTION%
depend: [MeepCore]
api-version: 1.15
commands:
  commandlog:
    aliases: [cl]
    description: Allows players to view commands used by others.
    usage: Use '/cl help' to show help information.
permissions:
  commandlog.notice:
    description: Allows players to be notified when a command is executed
    default: op
  commandlog.reload:
    description: Allows players to reload the plugin
    default: op
