name: CommandSpy
main: io.github.meeples10.commandspy.Main
version: %PROJECT_VERSION%
author: Meeples10
description: %PROJECT_DESCRIPTION%
depend: [MeepCore]
api-version: 1.19
commands:
  commandspy:
    aliases: [cspy]
    description: Allows players to view commands used by others.
    usage: Use '/cspy help' to show help information.
    permission: commandspy.use
permissions:
  commandspy.use:
    description: Allows players to use the /cspy command
    default: op
  commandspy.notice:
    description: Allows players to be notified when a command is executed
    default: op
  commandspy.reload:
    description: Allows players to reload the plugin
    default: op
